export const data = [
  {
    id: Math.round(Math.random() * 12345),
    url: "https://la.ua/wp-content/uploads/2021/08/2_belgisch-chocolade_icecream.png",
    title: "Морозиво Бельгійський шоколад",
    description:
      "молоко коров’яче, шоколад бельгійський (частка какао не менше 75%), цукор, виноградний цукор, цукровий сироп, ваніль натуральна",
    tableTitle: "Поживна харчова цінність на 100 г продукту:",
    tableItem1: "Білки",
    titleItem1: "5.7 г",
    tableItem2: "Вуглеводи",
    titleItem2: "20.8 г",
    tableItem3: "Жири",
    titleItem3: "4.3 г",
    tableItem4: "Калорійність",
    titleItem4: "157 ккал",
    price: 95,
    titlePrice: "грн",
    btnText: "Замовити",
    absoluteTitle: 230,
    absoluteDesc: "гр",
  },
  {
    id: Math.round(Math.random() * 12345),
    url: "https://la.ua/wp-content/uploads/2021/08/1_mango_icecream.png",
    title: "Морозиво Манго маракуйя",
    description: `молоко коров’яче, вершки коров’ячі, цукор, виноградний цукор, цукровий сироп, ксантанова камедь,камедь ріжкового дерева, натуральне пюре манго, натуральне`,
    tableTitle: "Поживна харчова цінність на 100 г продукту:",
    tableItem1: "Білки",
    titleItem1: "3.4 г",
    tableItem2: "Вуглеводи",
    titleItem2: "24.2 г",
    tableItem3: "Жири",
    titleItem3: "6 г",
    tableItem4: "Калорійність",
    titleItem4: "167 ккал",
    price: 105,
    titlePrice: "грн",
    btnText: "Замовити",
    absoluteTitle: 230,
    absoluteDesc: "гр",
  },
  {
    id: Math.round(Math.random() * 12345),
    url: "https://la.ua/wp-content/uploads/2021/08/3_pistachios_icecream.png",
    title: "Морозиво Сицілійська фісташка",
    description: `молоко коров’яче, вершки коров’ячі, цукор, виноградний цукор, цукровий сироп, ксантанова камедь,камедь ріжкового дерева, натуральне пюре манго, натуральне`,
    tableTitle: "Поживна харчова цінність на 100 г продукту:",
    tableItem1: "Білки",
    titleItem1: "3.4 г",
    tableItem2: "Вуглеводи",
    titleItem2: "24.2 г",
    tableItem3: "Жири",
    titleItem3: "6 г",
    tableItem4: "Калорійність",
    titleItem4: "167 ккал",
    price: 115,
    titlePrice: "грн",
    btnText: "Замовити",
    absoluteTitle: 230,
    absoluteDesc: "гр",
  },
  {
    id: Math.round(Math.random() * 12345),
    url: "https://la.ua/wp-content/uploads/2021/08/4_strachatella_icecream.png",
    title: "Морозиво Страчітелла",
    description: `молоко коров’яче, вершки коров’ячі, цукор, виноградний цукор, цукровий сироп, ксантанова камедь, камедь ріжкового дерева, шоколад бельгійський чорний`,
    tableTitle: "Поживна харчова цінність на 100 г продукту:",
    tableItem1: "Білки",
    titleItem1: "3.4 г",
    tableItem2: "Вуглеводи",
    titleItem2: "24.8 г",
    tableItem3: "Жири",
    titleItem3: "7.5 г",
    tableItem4: "Калорійність",
    titleItem4: "176 ккал",
    price: 95,
    titlePrice: "грн",
    btnText: "Замовити",
    absoluteTitle: 230,
    absoluteDesc: "гр",
  },
  {
    id: Math.round(Math.random() * 12345),
    url: "https://la.ua/wp-content/uploads/2021/08/6_lemon-mint_icecream.png",
    title: "Сорбет Лимон та м‘ята",
    description: `вода джерельна, цукор, цукровий сироп, виноградний цукор,камедь ріжкового дерева, гуарова камідь, фреш лимону, м’ята`,
    tableTitle: "Поживна харчова цінність на 100 г продукту:",
    tableItem1: "Білки",
    titleItem1: "0.3 г",
    tableItem2: "Вуглеводи",
    titleItem2: "26.2 г",
    tableItem3: "Жири",
    titleItem3: "0.2 г",
    tableItem4: "Калорійність",
    titleItem4: "144 ккал",
    price: 95,
    titlePrice: "грн",
    btnText: "Замовити",
    absoluteTitle: 230,
    absoluteDesc: "гр",
  },
  {
    id: Math.round(Math.random() * 12345),
    url: "https://la.ua/wp-content/uploads/2021/08/syrnyky.png",
    url2: "https://la.ua/wp-content/uploads/2021/08/navedennyz_syrnyky.png",
    title: "Сирники",
    description: `сирники, карамельний соус, сметана`,
    tableTitle: "Поживна харчова цінність на 100 г продукту:",
    tableItem1: "Білки",
    titleItem1: "15.3 г",
    tableItem2: "Вуглеводи",
    titleItem2: "13.6 г",
    tableItem3: "Жири",
    titleItem3: "14.3 г",
    tableItem4: "Калорійність",
    titleItem4: "247 ккал",
    price: 75,
    titlePrice: "грн",
    btnText: "Замовити",
    absoluteTitle: 240,
    absoluteDesc: "гр",
  },
  {
    id: Math.round(Math.random() * 12345),
    url: "https://la.ua/wp-content/uploads/2021/08/syrna-zapikanka.png",
    url2: "https://la.ua/wp-content/uploads/2021/08/navedennya_zapikanka.png",
    title: "Сирна запіканка",
    description: `сирна запіканка, ванільний соус, карамельний соус`,
    tableTitle: "Поживна харчова цінність на 100 г продукту:",
    tableItem1: "Білки",
    titleItem1: "8.2 г",
    tableItem2: "Вуглеводи",
    titleItem2: "15.5 г",
    tableItem3: "Жири",
    titleItem3: "9.9 г",
    tableItem4: "Калорійність",
    titleItem4: "189 ккал",
    price: 82,
    titlePrice: "грн",
    btnText: "Замовити",
    absoluteTitle: 240,
    absoluteDesc: "гр",
  },
  {
    id: Math.round(Math.random() * 12345),
    url: "https://la.ua/wp-content/uploads/2021/07/andruty-1.png",
    url2: "https://la.ua/wp-content/uploads/2021/07/navedennya_andruty.png",
    title: "Андрути",
    description: `вафлі, згущене молоко, горіхи`,
    tableTitle: "Поживна харчова цінність на 100 г продукту:",
    tableItem1: "Білки",
    titleItem1: "6.1 г",
    tableItem2: "Вуглеводи",
    titleItem2: "43.2 г",
    tableItem3: "Жири",
    titleItem3: "9.4 г",
    tableItem4: "Калорійність",
    titleItem4: "283 ккал",
    price: 65,
    titlePrice: "грн",
    btnText: "Замовити",
    absoluteTitle: 240,
    absoluteDesc: "гр",
  },
];
