export const data = [
  {
    id: Math.round(Math.random() * 12345),
    title: "Формаджіпесто",
    url: "https://la.ua/wp-content/uploads/2022/04/formadzhipestoformaggipesto-1.jpg",
    url2: "https://la.ua/wp-content/uploads/2022/04/formadzhipesto-2.jpg",
    description:
      "соус бешамель, сир моцарела, сир пармезан, сир камамбер, соус песто.",
    price: 215,
    titlePrice: "грн",
    weight: 400,
    weightTitle: "гр",
    size: 30,
    sizeTitle: "см",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Італіана",
    url: "https://la.ua/wp-content/uploads/2022/04/italyanaltaliana-1.jpg",
    url2: "https://la.ua/wp-content/uploads/2022/04/italyana-2.jpg",
    description:
      "соус бешамель, сир моцарела, курка, печериці, помідори чері, соус песто.",
    price: 205,
    titlePrice: "грн",
    weight: 510,
    weightTitle: "гр",
    size: 30,
    sizeTitle: "см",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Джавеліна",
    url: "https://la.ua/wp-content/uploads/2022/04/italyanaltaliana-1.jpg",
    url2: "https://la.ua/wp-content/uploads/2022/04/italyana-2.jpg",
    description:
      "соус кисло-солодкий, сир моцарела, курка, цибуля, баварські ковбаски, корнішон.",
    price: 210,
    titlePrice: "грн",
    weight: 475,
    weightTitle: "гр",
    size: 30,
    sizeTitle: "см",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Чіполла",
    url: "https://la.ua/wp-content/uploads/2022/04/chipolla-1.jpg",
    url2: "https://la.ua/wp-content/uploads/2022/04/chipolla-2.jpg",
    description: "соус барбекю, сир моцарела, салямі, печериці, цибуля.",
    price: 185,
    titlePrice: "грн",
    weight: 475,
    weightTitle: "гр",
    size: 30,
    sizeTitle: "см",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Піца La П’єц",
    url: "https://la.ua/wp-content/uploads/2021/08/la-pyets.jpg",
    url2: "https://la.ua/wp-content/uploads/2021/08/la-pyets-hover.jpg",
    description:
      "соус томатний, шинка, баварські ковбаски, сир моцарела, ковбаса салямі, прошуто.",
    price: 215,
    titlePrice: "грн",
    weight: 480,
    weightTitle: "гр",
    size: 30,
    sizeTitle: "см",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Цезаріо",
    url: "https://la.ua/wp-content/uploads/2021/08/tsezario.jpg",
    url2: "https://la.ua/wp-content/uploads/2021/08/tsezario-hover.jpg",
    description: `соус бешамель, помідори, хрусткий салат, пармезан, куряче м'ясо, сир моцарела, перепелині яйця, соус "Цезар".`,
    price: 241,
    titlePrice: "грн",
    weight: 600,
    weightTitle: "гр",
    size: 30,
    sizeTitle: "см",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Кватро формаджі",
    url: "https://la.ua/wp-content/uploads/2021/08/kvatro.jpg",
    url2: "https://la.ua/wp-content/uploads/2021/08/kvatro-hover.jpg",
    description: `соус бешамель, пармезан, сир моцарела, сир рікота, сир дорблю, волоський горіх, груша.`,
    price: 227,
    titlePrice: "грн",
    weight: 440,
    weightTitle: "гр",
    size: 30,
    sizeTitle: "см",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Капрічоза",
    url: "https://la.ua/wp-content/uploads/2021/08/capricciosa.jpg",
    url2: "https://la.ua/wp-content/uploads/2021/08/capricciosa-hover.jpg",
    description: `соус томатний, сир моцарела, шинка, свіжі гриби.`,
    price: 191,
    titlePrice: "грн",
    weight: 465,
    weightTitle: "гр",
    size: 30,
    sizeTitle: "см",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Гавайська",
    url: "https://la.ua/wp-content/uploads/2021/08/hawaiian.jpg",
    url2: "https://la.ua/wp-content/uploads/2021/08/hawaiian-hover.jpg",
    description: `сир моцарела, соус бешамель, філе куряче, кукурудза, ананас, оливки, перець болгарський.`,
    price: 185,
    titlePrice: "грн",
    weight: 540,
    weightTitle: "гр",
    size: 30,
    sizeTitle: "см",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Пепероні",
    url: "https://la.ua/wp-content/uploads/2021/08/peperoni.jpg",
    url2: "https://la.ua/wp-content/uploads/2021/08/peperoni-hover.jpg",
    description: `Рукола, сир моцарела, соус барбекю, пепероні, пармезан.`,
    price: 194,
    titlePrice: "грн",
    weight: 415,
    weightTitle: "гр",
    size: 30,
    sizeTitle: "см",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Карбонара",
    url: "https://la.ua/wp-content/uploads/2021/08/carbonara.jpg",
    url2: "https://la.ua/wp-content/uploads/2021/08/carbonara-hover.jpg",
    description: `соус томатний, шинка, запечене яйце, сир моцарела, баварські ковбаски.`,
    price: 192,
    titlePrice: "грн",
    weight: 485,
    weightTitle: "гр",
    size: 30,
    sizeTitle: "см",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Салямі",
    url: "https://la.ua/wp-content/uploads/2021/08/salyami.jpg",
    url2: "https://la.ua/wp-content/uploads/2021/08/salyami-hover.jpg",
    description: `соус томатний, сир моцарела, ковбаса салямі.`,
    price: 186,
    titlePrice: "грн",
    weight: 415,
    weightTitle: "гр",
    size: 30,
    sizeTitle: "см",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Панчетта",
    url: "https://la.ua/wp-content/uploads/2021/08/panchetta.jpg",
    url2: "https://la.ua/wp-content/uploads/2021/08/panchetta-hover.jpg",
    description: `сир моцарела, соус кисло-солодкий, грудинка свинна, перець болгарський, огірок корнішон.`,
    price: 189,
    titlePrice: "грн",
    weight: 435,
    weightTitle: "гр",
    size: 30,
    sizeTitle: "см",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Діабола",
    url: "https://la.ua/wp-content/uploads/2021/08/diabola.jpg",
    url2: "https://la.ua/wp-content/uploads/2021/08/diabola-hover.jpg",
    description: `соус томатний, сир моцарела, консервований перець чилі, ковбаса пепероні.`,
    price: 183,
    titlePrice: "грн",
    weight: 445,
    weightTitle: "гр",
    size: 30,
    sizeTitle: "см",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Маргарита",
    url: "https://la.ua/wp-content/uploads/2021/08/margarita.jpg",
    url2: "https://la.ua/wp-content/uploads/2021/08/margarita-hover.jpg",
    description: `соус томатний, сир моцарела, помідори.`,
    price: 139,
    titlePrice: "грн",
    weight: 420,
    weightTitle: "гр",
    size: 30,
    sizeTitle: "см",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Парма",
    url: "https://la.ua/wp-content/uploads/2021/08/parma-3.jpg",
    url2: "https://la.ua/wp-content/uploads/2021/08/parma-hover-2.jpg",
    description: `Рукола, соус бешамель, пармезан, сир моцарела, прошуто.`,
    price: 216,
    titlePrice: "грн",
    weight: 405,
    weightTitle: "гр",
    size: 30,
    sizeTitle: "см",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Шинкарелла",
    url: "https://la.ua/wp-content/uploads/2021/08/shynkarella.jpg",
    url2: "https://la.ua/wp-content/uploads/2021/08/shynkarella-hover.jpg",
    description: `соус томатний, сир моцарела, шинка.`,
    price: 181,
    titlePrice: "грн",
    weight: 415,
    weightTitle: "гр",
    size: 30,
    sizeTitle: "см",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Поло",
    url: "https://la.ua/wp-content/uploads/2021/08/polo.jpg",
    url2: "https://la.ua/wp-content/uploads/2021/08/polo-hover.jpg",
    description: `сир моцарела, цибуля, майонез, помідори, куряче м'ясо.`,
    price: 184,
    titlePrice: "грн",
    weight: 485,
    weightTitle: "гр",
    size: 30,
    sizeTitle: "см",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Тоно",
    url: "https://la.ua/wp-content/uploads/2021/08/tono.jpg",
    url2: "https://la.ua/wp-content/uploads/2021/08/tono-hover.jpg",
    description: `соус томатний, цибуля, тунець консервований, сир моцарела.`,
    price: 214,
    titlePrice: "грн",
    weight: 455,
    weightTitle: "гр",
    size: 30,
    sizeTitle: "см",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Аль сальмоне",
    url: "https://la.ua/wp-content/uploads/2021/08/salʹmone.jpg",
    url2: "https://la.ua/wp-content/uploads/2021/08/salʹmone-hover.jpg",
    description: `філе лосося, соус бешамель, сир моцарела, кунжут.`,
    price: 249,
    titlePrice: "грн",
    weight: 430,
    weightTitle: "гр",
    size: 30,
    sizeTitle: "см",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Меланзана",
    url: "https://la.ua/wp-content/uploads/2021/08/melanzana.jpg",
    url2: "https://la.ua/wp-content/uploads/2021/08/melanzana-hover.jpg",
    description: `соус бешамель, пармезан, сир моцарела, шинка, баклажани.`,
    price: 189,
    titlePrice: "грн",
    weight: 425,
    weightTitle: "гр",
    size: 30,
    sizeTitle: "см",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Кальцоне аль Форно",
    url: "https://la.ua/wp-content/uploads/2021/08/calzone.jpg",
    url2: "https://la.ua/wp-content/uploads/2021/08/calzone-hover.jpg",
    description: `соус томатний,  сир моцарела, сир рікота, шинка, помідори.`,
    price: 183,
    titlePrice: "грн",
    weight: 455,
    weightTitle: "гр",
    size: 30,
    sizeTitle: "см",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Вегетаріано",
    url: "https://la.ua/wp-content/uploads/2021/08/vega.jpg",
    url2: "https://la.ua/wp-content/uploads/2021/08/vega-hover.jpg",
    description: `соус бешамель, сир моцарела, печериці, перець болгарський, броколі.`,
    price: 182,
    titlePrice: "грн",
    weight: 490,
    weightTitle: "гр",
    size: 30,
    sizeTitle: "см",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Вітелло",
    url: "https://la.ua/wp-content/uploads/2021/08/vitello.jpg",
    url2: "https://la.ua/wp-content/uploads/2021/08/vitello-hover.jpg",
    description: `телятина, соус барбекю, сир моцарела, цибуля синя, огірок корнішон.`,
    price: 251,
    titlePrice: "грн",
    weight: 515,
    weightTitle: "гр",
    size: 30,
    sizeTitle: "см",
  },
];
