export const data = [
  {
    id: Math.round(Math.random() * 12345),
    title: "Салат Цезар зі смаженим курячим філе",
    url: "https://la.ua/wp-content/uploads/2021/08/tsezar-z-kurkoyu.png",
    ulr2:'https://la.ua/wp-content/uploads/2021/08/cezza-bigr.jpg',
    description:
      "Салат айсберг, помідори, куряче м`ясо, сир пармезан, перепелині яйця, духмяні сухарики та фірмова заправка - соус «Цезар».",
    price: 157,
    titlePrice: "грн",
    weight: 250,
    weightTitle: "гр",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Інсалата ді Сальмоне",
    url: 'https://la.ua/wp-content/uploads/2021/08/insalata-di-salmone1.png',
    ulr2:'https://la.ua/wp-content/uploads/2021/08/insalata-di-salmone-big-1.jpg',
    description:
      "Рукола, помідор чері, огірок, салат айсберг, соус айолі, пармезан, лосось, перепелине яйце, кунжут.",
    price: 162,
    titlePrice: "грн",
    weight: 285,
    weightTitle: "гр",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Прімавера",
    url: "https://la.ua/wp-content/uploads/2021/08/primavera.png",
    ulr2:'https://la.ua/wp-content/uploads/2021/08/primavera-big-1.jpg',
    description:
      "сир моцарела, салат айсберг, помідор чері, огірок, болгарський перець, оливкова олія, фреш лимонний, орегано.",
    price: 127,
    titlePrice: "грн",
    weight: 255,
    weightTitle: "гр",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Салат Цезар з телятиною",
    url: "https://la.ua/wp-content/uploads/2021/08/tsezar-z-telyatynoyu.png",
    ulr2:'https://la.ua/wp-content/uploads/2021/08/cezar-z-telyatynoyu-big_2.jpg',
    description:
      "Салат айсберг, помідори, телятина, сир пармезан, перепелині яйця, духмяні сухарики та фірмова заправка - соус «Цезар».",
    price: 189,
    titlePrice: "грн",
    weight: 250,
    weightTitle: "гр",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Інсалата ді Фета",
    url: "https://la.ua/wp-content/uploads/2021/08/feta.png",
    ulr2:'https://la.ua/wp-content/uploads/2021/08/insalata-big.jpg',
    description:
      "Салат айсберг, свіжі овочі, сир фета, кунжут, оливки, бальзамічна заправка.",
    price: 138,
    titlePrice: "грн",
    weight: 250,
    weightTitle: "гр",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Інсалата ді Прошуто",
    url: "https://la.ua/wp-content/uploads/2021/08/insalata-di-proshuto.png",
    ulr2:'https://la.ua/wp-content/uploads/2021/08/insalata-di-proshutto-big.jpg',
    description:
      "Рукола, салат айcберг, прошуто, сир пармезан, помідори, бальзамічна заправка.",
    price: 135,
    titlePrice: "грн",
    weight: 175,
    weightTitle: "гр",
  },
  {
    id: Math.round(Math.random() * 12345),
    title: "Інсалата ді Тоно",
    url: "https://la.ua/wp-content/uploads/2021/08/insalata-di-tono.png",
    ulr2:'https://la.ua/wp-content/uploads/2021/08/insalata-di-tono-big-1.jpg',
    description:
      "оливки, огірок, помідор чері, салат айсберг, оливкова олія, фреш лимонний, тунець, перепелине яйце, цибуля синя, кунжут.",
    price: 151,
    titlePrice: "грн",
    weight: 280,
    weightTitle: "гр",
  },
];
